[package]
name = "command"
version = "0.1.0"
edition = "2021"

[dependencies]
render_engine = { version = "0.1.0", path = "../render_engine" }
serde = { version = "1.0.217", default-features = false, features = ["derive"] }
