[package]
name = "render_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.26.0", default-features = false }

[features]
default = ["std"]
std = ["glam/std"]
