[package]
name = "rpi4"
version = "0.1.0"
edition = "2021"

[dependencies]
render_engine = { path = "../render_engine" }
ws2812-spi = "0.5.0"
smart-leds = "0.4.0"
ws281x-rpi = "0.0.1"
rppal = "0.19.0"

